### ISSUE TITLE
code completion issue for mysqli object

### ISSUE THREAD

**Issue by dalsword** [mackenza/Brackets-PHP-SmartHints#24]
After creating a new mysqli object as follows:
$db = new mysqli("localhost","user", "password","database");
Code assist does not bring "connect_errno" property after typing "mysqli->".

**Comment by mackenza** [comment]
code completion of objects is not in the extension yet.  I have it planned for the next major version but I have been very busy the last few months and development has tailed off somewhat for this extension.

**Comment by mackenza** [comment]
will be addressed in a future version.  Closing for now.
