### ISSUE TITLE
Make functions code hints case-insensitive

### ISSUE THREAD

**Issue by le717** [mackenza/Brackets-PHP-SmartHints#25]
As you are aware, functions in PHP are case-insensitive (though the usefulness of this fact is highly debatable). I think the function code hints should be as well. In my own brief PHP experience, I accidentally type an uppercase letter and code hints immediately stop. Making function hints case-insensitive would make this extension better in helping us write our ~~sad~~ PHP. :)

**Comment by mackenza** [comment]
@le717 I think this could be fairly easy to accomodate, but I wonder about what your expectations around the insertion are?

So if I type:
`myS` and a list pops open with the mysqli functions (for example) and I select `mysqli_connect` from the list, would you expect it to be inserted as `mysqli_connect` or `mySqli_connect` or even `mySQLI_CONNECT` or something like that?

I think it could suggest based on whatever case is entered to get a list up but the substitutions are always the case from the config file.  Agreed?

**Comment by le717** [comment]
Sounds good to me. :)

**Comment by le717** [comment]
> Sounds good to me. :)

And by that I meant

>I think it could suggest based on whatever case is entered to get a list up but the substitutions are always the case from the config file.

Just in case I wasn't clear.

**Comment by mackenza** [comment]
cool, I understood why you meant ;)

I will have a look at this.
