### ISSUE TITLE
mysql_fetch_assoc not showing

### ISSUE THREAD

**Issue by viktorstrate** [mackenza/Brackets-PHP-SmartHints#27]
A small thing but.<br>
The ```mysql_fetch_assoc``` doesn't show up as a hint, but all the other fetches do, like ``` mysql_fetch_array```<br>
```PHP
while($row = mysql_fetch_assoc($query))
```

**Comment by mackenza** [comment]
I am looking at this. . It seems to be a bug in how I am reading in the syntax strings.

**Comment by mackenza** [comment]
lol it turns out it was a major flaw in how I was parsing the function config files. There were dozens of hints being dropped not just mysql_fetch_assoc. 

Thanks for catching this. . I will have a fix out shortly. It might be a couple of days as I am travelling this week.
