### ISSUE TITLE
Hints turn off when accessing superglobal arrays

### ISSUE THREAD

**Issue by le717** [mackenza/Brackets-PHP-SmartHints#28]
Here's a quick GIF:

![php-hints-bug](https://cloud.githubusercontent.com/assets/3382464/6568305/bfbdf2dc-c6ab-11e4-8172-86da743af686.gif)

```php
<?php
  $_POST['book'];
  $_GET['ME'];
?>
```

**Comment by mackenza** [comment]
I will have a look.  What version are you on?

**Comment by le717** [comment]
Latest version, v1.1.5, Brackets 1.3 (from source). I've seen this for multiple Brackets and extension versions now.

**Comment by mackenza** [comment]
@le717 can install from master and see if your issue is fixed with my latest change?

**Comment by le717** [comment]
It works now. Thanks!

**Comment by le717** [comment]
Do want to close this or shall I? I usually let the repository maintainer close issues unless indicated otherwise. :)

**Comment by mackenza** [comment]
I will.  Thanks for the report
