### ISSUE TITLE
Two listings in extension registry

### ISSUE THREAD

**Issue by peterflynn** [mackenza/Brackets-PHP-SmartHints#29]
In the extension registry, I see:
[PHP-SIG] PHP SmartHints - version 1.1.3
PHP SmartHints - version 1.1.6

This seems confusing for users.  Both "More info" links lead here.  One should probably be removed from the listing.

**Comment by mackenza** [comment]
I totally forgot we controlled our own listings in the registry.  I removed the old PHP-SIG one.  Thanks @peterflynn
